### PR TITLE
Make it easier to understand the Dart-Sass installation part in READM…

### PR DESCRIPTION
**Pull request by yuptune**
…E.md

This pull request makes it easier to know which Dart-Sass to use.

### CODE REVIEW

**Comment by yuptune** [comment]
No, this WON'T break anything this time (unlike the compile-scss.sh pull request.)

**Comment by PF94** [comment]
"the one that uses bash" is vague

the release of dart sass that's used is from the GitHub releases page of dart sass

**Comment by yuptune** [comment]
i'll make a new commit, hold on

**Comment by yuptune** [comment]
Changed.

**Comment by yuptune** [comment]
I have now made a new commit

**Pull request merged**
