### PR TITLE
link to .pw and fulptube.rocks as alternative domains

### PR DESCRIPTION
**Pull request by sdpj**
idk i think it looks cool

### CODE REVIEW

**Comment by yuptune** [comment]
this is not needed

**Comment by sdpj** [comment]
shut up luna

**Comment by yuptune** [comment]
make me

**Comment by sdpj** [comment]
https://github.com/user-attachments/assets/436b4546-98a2-47aa-b1f0-3c9dd4008093

**Comment by PF94** [comment]
this is missing flowerz's squarebracket.lol domain

**Pull request merged**
