### PR TITLE
the whois verification shit was fixed AGES ago lol

### PR DESCRIPTION
**Pull request by nixtyninee**

### CODE REVIEW

**Comment by PF94** [comment]
this is not an official domain

**Comment by nixtyninee** [comment]
https://github.com/bluffingo/OpenSB/commit/94b716cbc1d42faa409e30301aaa288daba3ef14

**Comment by PF94** [comment]
this is regardless, still not an official domain. opensb purposefully does not count views coming from squarebracket.lol.

**Comment by nixtyninee** [comment]
its regardless that you literally had it on the readme before? i am not about to get into it with you over fucking github check ur messages if its rlly that deep

**Pull request closed without merging**
