### PR TITLE
remove the changes i made

### PR DESCRIPTION
**Pull request by sdpj**
clearly i am not needed at squarebracket!

### CODE REVIEW

**Comment by PF94** [comment]
this is petty

**Comment by sdpj** [comment]
> this is petty

dawg you hired the most power hungry mf ever and fired the entire staff team 😭

**Comment by PF94** [comment]
image

Makes you wonder why was i gonna leave sb until the raid shit happened

**Comment by sdpj** [comment]
> image
> 
> Makes you wonder why was i gonna leave sb until the raid shit happened

so _why_ did you fire everyone?

**Pull request closed without merging**
